version: '3.9'
services:
  server:
    build: ./server  # Path to your server directory
    ports:
      - "5000:5000"   # Expose port 5000 from the container to the host
    networks:
      - client-server-network

  client:
    build: ./client  # Path to your client directory
    depends_on:
      - server        # Make sure server is up before starting the client
    networks:
      - client-server-network

networks:
  client-server-network:
    driver: bridge
